name: Exit Prerelease Mode
on:
  workflow_dispatch:

# Wait for the workflow to finish before starting a new one
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-beta:
    # Only allow on master branch
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    # More info: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.10

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Exit prerelease mode and commit the changes
      - name: Exit Prerelease Mode
        run: |
          pnpm changeset pre exit
          git add .
          git commit -m "chore: exit prerelease mode"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
