name: Release Stable
on:
  workflow_dispatch:
    inputs:
      selected-package:
        description: 'Package to version and publish to npm.'
        required: false
        default: 'all'
        type: choice
        options:
          - 'all'
          - '@martines3000/core'
          - '@martines3000/lib-1'
          - '@martines3000/lib-2'
          - '@martines3000/lib-3'

# Wait for the workflow to finish before starting a new one
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-stable:
    # Only allow on master branch
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    # More info: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.10

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Makes a pr to publish the changesets (when merged will publish to npm)
      # see https://github.com/changesets/action
      - name: Publish To NPM or Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          publish: bash scripts/publish-stable.sh
          version: |
            export SELECTED_PACKAGE=${{ github.event.inputs.selected-package }}
            bash scripts/version-stable.sh
          title: 'chore: version packages (stable)'
          commit: 'chore: version packages (stable)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
