name: Version Stable
on:
  workflow_dispatch:
    inputs:
      selected-package:
        description: 'Package to version and publish to npm.'
        required: false
        default: 'all'
        type: choice
        options:
          - 'all'
          - '@martines3000/core'
          - '@martines3000/lib-1'
          - '@martines3000/lib-2'
          - '@martines3000/lib-3'

# Wait for the workflow to finish before starting a new one
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-stable:
    # Only allow on master branch
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    # More info: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.10

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Version packages
        run: bash scripts/version-stable.sh ${{ github.event.inputs.selected-package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
